# Generated by Django 3.2.3 on 2021-09-30 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Поставщик')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активность')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Ед измереения')),
            ],
            options={
                'verbose_name': 'Ед измерения',
                'verbose_name_plural': 'Ед измерения',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Название продукта')),
                ('key', models.CharField(max_length=50, verbose_name='Ключ продукта')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена продукта')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.provider', verbose_name='Поставщик')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.unit', verbose_name='Ед измерения')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['name', 'provider'],
            },
        ),
    ]
