# Generated by Django 3.2.3 on 2021-09-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_products_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='amount_in_box',
            field=models.CharField(default=1, max_length=10, verbose_name='Кол-во в коробке'),
        ),
    ]
